include $(BASE_DIR)/kernel/mm/makefile
include $(BASE_DIR)/kernel/sched/makefile
include $(BASE_DIR)/kernel/symbol_table/makefile
include $(BASE_DIR)/kernel/loader/makefile
include $(BASE_DIR)/kernel/irq/makefile

C_SOURCES    += \
		$(wildcard $(BASE_DIR)/kernel/*.c)

