include $(BASE_DIR)/arch/$(STRUCT)/boot/makefile
include $(BASE_DIR)/arch/$(STRUCT)/config/makefile.$(PLATFORM)

include $(BASE_DIR)/arch/$(STRUCT)/kernel/irq/makefile
include $(BASE_DIR)/arch/$(STRUCT)/kernel/sched/makefile
include $(BASE_DIR)/arch/$(STRUCT)/kernel/syscall/makefile

