include $(BASE_DIR)/arch/$(STRUCT)/boot/makefile

include $(BASE_DIR)/arch/$(STRUCT)/kernel/irq/makefile
include $(BASE_DIR)/arch/$(STRUCT)/kernel/sched/makefile
include $(BASE_DIR)/arch/$(STRUCT)/kernel/syscall/makefile
include $(BASE_DIR)/arch/$(STRUCT)/kernel/start/makefile
include $(BASE_DIR)/arch/$(STRUCT)/kernel/err/makefile

include $(BASE_DIR)/arch/$(STRUCT)/mach-$(VENDOR)/$(PLATFORM)/makefile 
