include $(BASE_DIR)/fs/devfs/makefile
include $(BASE_DIR)/fs/pipefs/makefile
include $(BASE_DIR)/fs/initramfs/makefile
include $(BASE_DIR)/fs/ext2/Makefile
include $(BASE_DIR)/fs/sysfs/Makefile

C_SOURCES    += \
		$(wildcard $(BASE_DIR)/fs/*.c)

