# include ./lib/asm-generic/Makefile
include $(BASE_DIR)/lib/fdt/makefile
include $(BASE_DIR)/lib/script/makefile
include $(BASE_DIR)/lib/sys/makefile

C_SOURCES    += \
		$(wildcard $(BASE_DIR)/lib/*.c)


