include $(BASE_DIR)/drivers/clock/makefile
include $(BASE_DIR)/drivers/tty/makefile
include $(BASE_DIR)/drivers/gpio/makefile
include $(BASE_DIR)/drivers/spi/makefile
include $(BASE_DIR)/drivers/tick/makefile


C_SOURCES    += \
		$(wildcard $(BASE_DIR)/drivers/*.c)


include $(BASE_DIR)/drivers/storage/makefile
