include ./drivers/clock/makefile
include ./drivers/tty/makefile
include ./drivers/gpio/makefile
include ./drivers/spi/makefile
include ./drivers/tick/makefile


C_SOURCES    += \
		$(wildcard ./drivers/*.c)


include ./drivers/storage/makefile
